name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker image
      run: |
        docker build -t mrxm/flask-app:latest .
        docker push mrxm/flask-app:latest

    - name: Update deployment manifest
      run: |
        sed -i "s|image: .*|image: mrxm/flask-app:latest|" k8s/deployment.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s/deployment.yaml
        git commit -m "Update image tag"
        git push
